apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: game-stream
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: game-stream-sa
      containers:
        - name: backend
          image: ghcr.io/example/game-stream-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ORCHESTRATOR
              value: kubernetes
            - name: K8S_NAMESPACE
              value: game-stream
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: game-stream
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  type: ClusterIP
