/* gen_headers/fc_config.h.  Generated from fc_config.h.in by configure.  */
/* gen_headers/fc_config.h.in.  Generated from configure.ac by autoheader.  */

/* This header file is shipped in some binary distributions.
 * It is included purely for reference as to how the executables were built,
 * and changing it will have no functional effect on pre-built binaries. */

/* Define if building universal (internal helper macro) */
/* #undef AC_APPLE_UNIVERSAL_BUILD */

/* Enable ai modules */
/* #undef AI_MODULES */

/* Default ai type name */
#define AI_MOD_DEFAULT "classic"

/* classic ai module statically linked */
#define AI_MOD_STATIC_CLASSIC 1

/* stub ai module statically linked */
/* #undef AI_MOD_STATIC_STUB */

/* experimental threads ai module statically linked */
#define AI_MOD_STATIC_TEX 1

/* threaded ai module statically linked */
/* #undef AI_MOD_STATIC_THREADED */

/* Can execute program as root - Amiga */
/* #undef ALWAYS_ROOT */

/* SDL Mixer support */
#define AUDIO_SDL 1

/* Bug reporting URL */
#define BUG_URL "https://redmine.freeciv.org/projects/freeciv"

/* this is crosser based build */
/* #undef CROSSER */

/* Path to CA cert bundle */
/* #undef CUSTOM_CACERT_PATH */

/* Version specific subdir for default data path */
#define DATASUBDIR "3.1"

/* Connection TCP Port */
#define DEFAULT_SOCK_PORT 5556

/* Emergency version */
/* #undef EMERGENCY_VERSION */

/* Define to 1 if translation of program messages to the user's native
   language is requested. */
#define ENABLE_NLS 1

/* Configuration autogenerated */
#define FC_CONFIG_H 1

/* this is Qt5 based build */
/* #undef FC_QT5_MODE */

/* These are the CFLAGS used in compilation */
#define FC_STORE_CFLAGS "-Wall -Wpointer-arith -Wcast-align -Wno-tautological-compare -I/opt/homebrew/include"

/* These are the CPPFLAGS used in compilation */
#define FC_STORE_CPPFLAGS "-I/opt/homebrew/opt/icu4c/include -I/opt/homebrew/include -DLOCALEDIR=\"\\\"${datarootdir}/locale\\\"\" -DBINDIR=\"\\\"${exec_prefix}/bin\\\"\" -DFC_CONF_PATH=\"\\\"${prefix}/etc/freeciv\\\"\" -DDEFAULT_DATA_PATH=\"\\\".:data:~/.freeciv/3.1:${datarootdir}/freeciv\\\"\" -DDEFAULT_SAVE_PATH=\"\\\".:~/.freeciv/saves\\\"\" -DDEFAULT_SCENARIO_PATH=\"\\\".:data/scenarios:~/.freeciv/3.1/scenarios:~/.freeciv/scenarios:${datarootdir}/freeciv/scenarios\\\"\""

/* These are the CXXFLAGS used in compilation */
#define FC_STORE_CXXFLAGS "-Wall -Wpointer-arith -Wcast-align -Wno-tautological-compare -Wno-deprecated-declarations -g -O2"

/* Version tag to follow */
#define FOLLOWTAG "stable"

/* Max number of AI modules */
#define FREECIV_AI_MOD_LAST (0+1+1)

/* C11 static assert supported */
#define FREECIV_C11_STATIC_ASSERT 1

/* this is crosser based build */
/* #undef FREECIV_CROSSER */

/* C++11 static assert supported */
#define FREECIV_CXX11_STATIC_ASSERT 1

/* Extra debugging support */
/* #undef FREECIV_DEBUG */

/* Delta protocol enabled */
#define FREECIV_DELTA_PROTOCOL 1

/* Distribution this freeciv is built for */
#define FREECIV_DISTRIBUTOR ""

/* Native language support enabled */
#define FREECIV_ENABLE_NLS 1

/* Use C11 threads as thread implementation */
/* #undef FREECIV_HAVE_C11_THREADS */

/* C++20 capture 'this' supported */
/* #undef FREECIV_HAVE_CXX20_CAPTURE_THIS */

/* dirent.h available */
#define FREECIV_HAVE_DIRENT_H 1

/* inttypes.h available */
#define FREECIV_HAVE_INTTYPES_H 1

/* libbzip2 is available */
#define FREECIV_HAVE_LIBBZ2 1

/* libint.h available */
#define FREECIV_HAVE_LIBINTL_H 1

/* liblzma is available */
#define FREECIV_HAVE_LIBLZMA 1

/* Readline support */
/* #undef FREECIV_HAVE_LIBREADLINE */

/* zlib is available */
#define FREECIV_HAVE_LIBZ 1

/* libzstd is available */
#define FREECIV_HAVE_LIBZSTD 1

/* locale.h available */
#define FREECIV_HAVE_LOCALE_H 1

/* netinet/in.h available */
#define FREECIV_HAVE_NETINET_IN_H 1

/* opendir() available */
#define FREECIV_HAVE_OPENDIR 1

/* Use pthreads as thread implementation */
#define FREECIV_HAVE_PTHREAD 1

/* Have socklen_t type defined */
#define FREECIV_HAVE_SOCKLEN_T 1

/* Have standard compliant stdbool.h */
#define FREECIV_HAVE_STDBOOL_H 1

/* stdint.h available */
#define FREECIV_HAVE_STDINT_H 1

/* sys/select.h available */
#define FREECIV_HAVE_SYS_SELECT_H 1

/* sys/socket.h available */
#define FREECIV_HAVE_SYS_SOCKET_H 1

/* sys/time.h available */
#define FREECIV_HAVE_SYS_TIME_H 1

/* sys/types.h available */
#define FREECIV_HAVE_SYS_TYPES_H 1

/* Has thread condition variable implementation */
#define FREECIV_HAVE_THREAD_COND 1

/* Use tinycthread as thread implementation */
/* #undef FREECIV_HAVE_TINYCTHR */

/* unistd.h available */
#define FREECIV_HAVE_UNISTD_H 1

/* Mingw-specific setting - winsock */
/* #undef FREECIV_HAVE_WINSOCK */

/* Mingw-specific setting - winsock2 */
/* #undef FREECIV_HAVE_WINSOCK2 */

/* Use Windows threads as thread implementation */
/* #undef FREECIV_HAVE_WINTHREADS */

/* ws2tcpip.h available */
/* #undef FREECIV_HAVE_WS2TCPIP_H */

/* Build xml-backend for registry */
/* #undef FREECIV_HAVE_XML_REGISTRY */

/* IPv6 Support built in */
#define FREECIV_IPV6_SUPPORT 1

/* jansson network protocol in use */
/* #undef FREECIV_JSON_CONNECTION */

/* Json Connection TCP Port */
#define FREECIV_JSON_PORT 6556

/* Metaserver URL */
#define FREECIV_META_URL "https://meta.freeciv.org/metaserver.php"

/* Windows build */
/* #undef FREECIV_MSWINDOWS */

/* MagickWand version 7 API in use */
#define FREECIV_MWAND7 1

/* No freeciv specific debugging support at all */
/* #undef FREECIV_NDEBUG */

/* [Var arg cannot be const] */
#define FREECIV_NO_CONST_VAR_ARG 1

/* Client is very patient when connecting to spawned server */
/* #undef FREECIV_PATIENT_CONNECT */

/* Month next version will be released */
#define FREECIV_RELEASE_MONTH 3

/* [Value must be returned even after exit()] */
/* #undef FREECIV_RETURN_VALUE_AFTER_EXIT */

/* Mingw-specific setting - stdin */
/* #undef FREECIV_SOCKET_ZERO_NOT_STDIN */

/* strlen() in static assert supported */
#define FREECIV_STATIC_STRLEN 1

/* Location for freeciv to store its information */
#define FREECIV_STORAGE_DIR "~/.freeciv"

/* Testmatic integration enabled */
/* #undef FREECIV_TESTMATIC */

/* Build freeciv-web version instead of regular freeciv */
/* #undef FREECIV_WEB */

/* Get git revision information to version number */
/* #undef GITREV */

/* Define to 1 if you have the <arpa/inet.h> header file. */
#define HAVE_ARPA_INET_H 1

/* C11 at_quick_exit() available */
#define HAVE_AT_QUICK_EXIT 1

/* Define to 1 if you have the 'backtrace' function. */
#define HAVE_BACKTRACE 1

/* BCryptGenRandom() available */
/* #undef HAVE_BCRYPTGENRANDOM */

/* Define to 1 if you have the <bcrypt.h> header file. */
/* #undef HAVE_BCRYPT_H */

/* Define to 1 if you have the 'bind' function. */
#define HAVE_BIND 1

/* Define to 1 if you have the <bzlib.h> header file. */
#define HAVE_BZLIB_H 1

/* Define to 1 if you have the Mac OS X function
   CFLocaleCopyPreferredLanguages in the CoreFoundation framework. */
#define HAVE_CFLOCALECOPYPREFERREDLANGUAGES 1

/* Define to 1 if you have the Mac OS X function CFPreferencesCopyAppValue in
   the CoreFoundation framework. */
#define HAVE_CFPREFERENCESCOPYAPPVALUE 1

/* Define to 1 if you have the 'clock_gettime' function. */
#define HAVE_CLOCK_GETTIME 1

/* Define to 1 if you have the 'connect' function. */
#define HAVE_CONNECT 1

/* Define to 1 if you have the <cstddef> header file. */
#define HAVE_CSTDDEF 1

/* libcurl has the mime api */
#define HAVE_CURL_MIME_API 1

/* define if the compiler supports basic C++11 syntax */
/* #undef HAVE_CXX11 */

/* define if the compiler supports basic C++17 syntax */
#define HAVE_CXX17 1

/* Define if the GNU dcgettext() function is already present or preinstalled.
   */
#define HAVE_DCGETTEXT 1

/* Define to 1 if you have the <direct.h> header file. */
/* #undef HAVE_DIRECT_H */

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you don't have 'vprintf' but do have '_doprnt.' */
/* #undef HAVE_DOPRNT */

/* Define to 1 if you have the <execinfo.h> header file. */
#define HAVE_EXECINFO_H 1

/* Database backend available */
#define HAVE_FCDB 1

/* Have MySQL database backend */
/* #undef HAVE_FCDB_MYSQL */

/* Have ODBC database backend */
/* #undef HAVE_FCDB_ODBC */

/* Have postgres database backend */
/* #undef HAVE_FCDB_POSTGRES */

/* Have Sqlite3 database backend */
#define HAVE_FCDB_SQLITE3 1

/* fcntl support */
#define HAVE_FCNTL 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the 'fdopen' function. */
#define HAVE_FDOPEN 1

/* Define to 1 if you have the 'fileno' function. */
#define HAVE_FILENO 1

/* Define to 1 if you have the 'flock' function. */
#define HAVE_FLOCK 1

/* Define to 1 if you have the 'fopen_s' function. */
/* #undef HAVE_FOPEN_S */

/* Define to 1 if you have the 'fork' function. */
#define HAVE_FORK 1

/* Define to 1 if fseeko (and ftello) are declared in stdio.h. */
#define HAVE_FSEEKO 1

/* Define to 1 if you have the 'ftime' function. */
#define HAVE_FTIME 1

/* Define to 1 if you have the 'getaddrinfo' function. */
#define HAVE_GETADDRINFO 1

/* Define to 1 if you have the 'getcwd' function. */
#define HAVE_GETCWD 1

/* Define to 1 if you have the 'getentropy' function. */
#define HAVE_GETENTROPY 1

/* Define to 1 if you have the 'gethostbyname' function. */
#define HAVE_GETHOSTBYNAME 1

/* Define to 1 if you have the 'gethostname' function. */
#define HAVE_GETHOSTNAME 1

/* Define to 1 if you have the 'getline' function. */
#define HAVE_GETLINE 1

/* Define to 1 if you have the 'getnameinfo' function. */
#define HAVE_GETNAMEINFO 1

/* Define to 1 if you have the 'getpwuid' function. */
#define HAVE_GETPWUID 1

/* Define if the GNU gettext() function is already present or preinstalled. */
#define HAVE_GETTEXT 1

/* Define if the gettimeofday function works and is sane. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have the 'gmtime_r' function. */
#define HAVE_GMTIME_R 1

/* Define if you have the iconv() function and it works. */
/* #undef HAVE_ICONV */

/* Define to 1 if you have the 'inet_aton' function. */
#define HAVE_INET_ATON 1

/* Define to 1 if you have the 'inet_ntop' function. */
#define HAVE_INET_NTOP 1

/* Define to 1 if you have the 'inet_pton' function. */
#define HAVE_INET_PTON 1

/* Define to 1 if the system has the type 'intptr_t'. */
#define HAVE_INTPTR_T 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* ioctl support */
/* #undef HAVE_IOCTL */

/* struct ip_mreqn available */
#define HAVE_IP_MREQN 1

/* Define if you have <langinfo.h> and nl_langinfo(CODESET). */
#define HAVE_LANGINFO_CODESET 1

/* Define if you have <libcharset.h> and locale_charset(). */
#define HAVE_LIBCHARSET 1

/* Define to 1 if you have the <libgen.h> header file. */
#define HAVE_LIBGEN_H 1

/* Define to 1 if you have the <libintl.h> header file. */
#define HAVE_LIBINTL_H 1

/* Define to 1 if you have the 'nls' library (-lnls). */
/* #undef HAVE_LIBNLS */

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the 'localtime_r' function. */
#define HAVE_LOCALTIME_R 1

/* Define to 1 if you have the <lzma.h> header file. */
#define HAVE_LZMA_H 1

/* Have magickwand mapimg toolkit */
#define HAVE_MAPIMG_MAGICKWAND 1

/* Define to 1 if you have the <minix/config.h> header file. */
/* #undef HAVE_MINIX_CONFIG_H */

/* Have working mkstemp */
#define HAVE_MKSTEMP 1

/* Define to 1 if you have the 'nanosleep' function. */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have the <netdb.h> header file. */
#define HAVE_NETDB_H 1

/* Define to 1 if you have the <netinet/in.h> header file. */
#define HAVE_NETINET_IN_H 1

/* Define to 1 if you have the 'opendir' function. */
#define HAVE_OPENDIR 1

/* Define to 1 if you have the 'pclose' function. */
#define HAVE_PCLOSE 1

/* Define to 1 if you have the 'popen' function. */
#define HAVE_POPEN 1

/* Define to 1 if you have the 'putenv' function. */
#define HAVE_PUTENV 1

/* Define to 1 if you have the <pwd.h> header file. */
#define HAVE_PWD_H 1

/* Define to 1 if you have the 'select' function. */
#define HAVE_SELECT 1

/* Define to 1 if you have the 'setenv' function. */
#define HAVE_SETENV 1

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* sigpipe support */
#define HAVE_SIGPIPE 1

/* Define to 1 if you have the 'snooze' function. */
/* #undef HAVE_SNOOZE */

/* Define to 1 if the system has the type 'socklen_t'. */
#define HAVE_SOCKLEN_T 1

/* Define to 1 if you have the <sqlext.h> header file. */
/* #undef HAVE_SQLEXT_H */

/* Define to 1 if you have the <sqltypes.h> header file. */
/* #undef HAVE_SQLTYPES_H */

/* Define to 1 if you have the <sql.h> header file. */
/* #undef HAVE_SQL_H */

/* Define to 1 if stdbool.h conforms to C99. */
#define HAVE_STDBOOL_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdio.h> header file. */
#define HAVE_STDIO_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the 'strcasecoll' function. */
/* #undef HAVE_STRCASECOLL */

/* Define to 1 if you have the 'strcasestr' function. */
#define HAVE_STRCASESTR 1

/* Define to 1 if you have the 'strcoll' function and it is properly defined.
   */
#define HAVE_STRCOLL 1

/* Define to 1 if you have the 'strerror' function. */
#define HAVE_STRERROR 1

/* Define to 1 if you have the 'stricoll' function. */
/* #undef HAVE_STRICOLL */

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the 'strstr' function. */
#define HAVE_STRSTR 1

/* Define to 1 if you have the <sys/file.h> header file. */
#define HAVE_SYS_FILE_H 1

/* Define to 1 if you have the <sys/ioctl.h> header file. */
#define HAVE_SYS_IOCTL_H 1

/* Define to 1 if you have the <sys/random.h> header file. */
#define HAVE_SYS_RANDOM_H 1

/* Define to 1 if you have the <sys/select.h> header file. */
#define HAVE_SYS_SELECT_H 1

/* Define to 1 if you have the <sys/signal.h> header file. */
#define HAVE_SYS_SIGNAL_H 1

/* Define to 1 if you have the <sys/socket.h> header file. */
#define HAVE_SYS_SOCKET_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/termio.h> header file. */
/* #undef HAVE_SYS_TERMIO_H */

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/uio.h> header file. */
#define HAVE_SYS_UIO_H 1

/* Define to 1 if you have the <sys/utsname.h> header file. */
#define HAVE_SYS_UTSNAME_H 1

/* Define to 1 if you have <sys/wait.h> that is POSIX.1 compatible. */
#define HAVE_SYS_WAIT_H 1

/* Define to 1 if you have the <termios.h> header file. */
#define HAVE_TERMIOS_H 1

/* Define to 1 if you have the <time.h> header file. */
#define HAVE_TIME_H 1

/* Define to 1 if you have the 'uname' function. */
#define HAVE_UNAME 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Build in /dev/urandom support */
#define HAVE_USABLE_URANDOM 1

/* Define to 1 if you have the 'usleep' function. */
#define HAVE_USLEEP 1

/* va_copy() available */
#define HAVE_VA_COPY 1

/* Define to 1 if you have the 'vfork' function. */
#define HAVE_VFORK 1

/* Define to 1 if you have the <vfork.h> header file. */
/* #undef HAVE_VFORK_H */

/* Define to 1 if you have the 'vprintf' function. */
#define HAVE_VPRINTF 1

/* Define to 1 if you have the 'vsnprintf' function. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if 'fork' works. */
#define HAVE_WORKING_FORK 1

/* Define to 1 if 'vfork' works. */
#define HAVE_WORKING_VFORK 1

/* Define if you have a version of the 'vsnprintf' function that honours the
   size argument and has a proper return value. */
#define HAVE_WORKING_VSNPRINTF 1

/* Define to 1 if you have the <ws2tcpip.h> header file. */
/* #undef HAVE_WS2TCPIP_H */

/* Define to 1 if you have the <zstd.h> header file. */
#define HAVE_ZSTD_H 1

/* Define to 1 if the system has the type '_Bool'. */
#define HAVE__BOOL 1

/* Define to 1 if you have the file '/dev/urandom'. */
#define HAVE__DEV_URANDOM 1

/* Define to 1 if you have the '_longjmp' function. */
#define HAVE__LONGJMP 1

/* Define to 1 if you have the '_mkdir' function. */
/* #undef HAVE__MKDIR */

/* Define to 1 if you have the '_setjmp' function. */
#define HAVE__SETJMP 1

/* Define to 1 if you have the '_strcoll' function. */
/* #undef HAVE__STRCOLL */

/* Define to 1 if you have the '_stricoll' function. */
/* #undef HAVE__STRICOLL */

/* Define as const if the declaration of iconv() needs const. */
#define ICONV_CONST 

/* Beginning of C99 structure initializer */
#define INIT_BRACE_BEGIN {

/* End of C99 structure initializer */
#define INIT_BRACE_END }

/* Is this a beta version */
#define IS_BETA_VERSION 0

/* Is this a devel version */
#define IS_DEVEL_VERSION 0

/* Is this a frozen version */
#define IS_FREEZE_VERSION 0

/* Locale directory (windows) */
/* #undef LOCALEDIR */

/* Define to the sub-directory where libtool stores uninstalled libraries. */
#define LT_OBJDIR ".libs/"

/* Lua Api checks */
/* #undef LUA_USE_APICHECK */

/* Major version */
#define MAJOR_VERSION 3

/* It's ok to call malloc() for zero bytes */
#define MALLOC_ZERO_OK 1

/* Minor version */
#define MINOR_VERSION 1

/* Default modpack list URL */
/* #undef MODPACK_LIST_URL */

/* No debugging support at all */
/* #undef NDEBUG */

/* Version number of next release */
#define NEXT_STABLE_VERSION "3.1.0"

/* nonblocking sockets support */
#define NONBLOCKING_SOCKETS 1

/* Name of package */
#define PACKAGE "freeciv"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "https://redmine.freeciv.org/projects/freeciv"

/* Define to the full name of this package. */
#define PACKAGE_NAME "Freeciv"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "Freeciv 3.1.5"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "freeciv"

/* Define to the home page for this package. */
#define PACKAGE_URL "https://www.freeciv.org/"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.1.5"

/* Patch version */
#define PATCH_VERSION 5

/* Qt debugging support disabled */
#define QT_NO_DEBUG 1

/* build experimental features to freeciv-ruledit */
/* #undef RULEDIT_EXPERIMENTAL */

/* sdl2 headers must be included without path */
/* #undef SDL2_PLAIN_INCLUDE */

/* The size of 'int', as computed by sizeof. */
#define SIZEOF_INT 4

/* Format specifier for size_t */
#define SIZE_T_PRINTF "%zu"

/* Define to 1 if all of the C89 standard headers exist (not just the ones
   required in a freestanding environment). This macro is provided for
   backward compatibility; new code need not use it. */
#define STDC_HEADERS 1

/* Define to 1 if your <sys/time.h> declares 'struct tm'. */
/* #undef TM_IN_SYS_TIME */

/* Enable extensions on AIX, Interix, z/OS.  */
#ifndef _ALL_SOURCE
# define _ALL_SOURCE 1
#endif
/* Enable general extensions on macOS.  */
#ifndef _DARWIN_C_SOURCE
# define _DARWIN_C_SOURCE 1
#endif
/* Enable general extensions on Solaris.  */
#ifndef __EXTENSIONS__
# define __EXTENSIONS__ 1
#endif
/* Enable GNU extensions on systems that have them.  */
#ifndef _GNU_SOURCE
# define _GNU_SOURCE 1
#endif
/* Enable X/Open compliant socket functions that do not require linking
   with -lxnet on HP-UX 11.11.  */
#ifndef _HPUX_ALT_XOPEN_SOCKET_API
# define _HPUX_ALT_XOPEN_SOCKET_API 1
#endif
/* Identify the host operating system as Minix.
   This macro does not affect the system headers' behavior.
   A future release of Autoconf may stop defining this macro.  */
#ifndef _MINIX
/* # undef _MINIX */
#endif
/* Enable general extensions on NetBSD.
   Enable NetBSD compatibility extensions on Minix.  */
#ifndef _NETBSD_SOURCE
# define _NETBSD_SOURCE 1
#endif
/* Enable OpenBSD compatibility extensions on NetBSD.
   Oddly enough, this does nothing on OpenBSD.  */
#ifndef _OPENBSD_SOURCE
# define _OPENBSD_SOURCE 1
#endif
/* Define to 1 if needed for POSIX-compatible behavior.  */
#ifndef _POSIX_SOURCE
/* # undef _POSIX_SOURCE */
#endif
/* Define to 2 if needed for POSIX-compatible behavior.  */
#ifndef _POSIX_1_SOURCE
/* # undef _POSIX_1_SOURCE */
#endif
/* Enable POSIX-compatible threading on Solaris.  */
#ifndef _POSIX_PTHREAD_SEMANTICS
# define _POSIX_PTHREAD_SEMANTICS 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-5:2014.  */
#ifndef __STDC_WANT_IEC_60559_ATTRIBS_EXT__
# define __STDC_WANT_IEC_60559_ATTRIBS_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-1:2014.  */
#ifndef __STDC_WANT_IEC_60559_BFP_EXT__
# define __STDC_WANT_IEC_60559_BFP_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-2:2015.  */
#ifndef __STDC_WANT_IEC_60559_DFP_EXT__
# define __STDC_WANT_IEC_60559_DFP_EXT__ 1
#endif
/* Enable extensions specified by C23 Annex F.  */
#ifndef __STDC_WANT_IEC_60559_EXT__
# define __STDC_WANT_IEC_60559_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TS 18661-4:2015.  */
#ifndef __STDC_WANT_IEC_60559_FUNCS_EXT__
# define __STDC_WANT_IEC_60559_FUNCS_EXT__ 1
#endif
/* Enable extensions specified by C23 Annex H and ISO/IEC TS 18661-3:2015.  */
#ifndef __STDC_WANT_IEC_60559_TYPES_EXT__
# define __STDC_WANT_IEC_60559_TYPES_EXT__ 1
#endif
/* Enable extensions specified by ISO/IEC TR 24731-2:2010.  */
#ifndef __STDC_WANT_LIB_EXT2__
# define __STDC_WANT_LIB_EXT2__ 1
#endif
/* Enable extensions specified by ISO/IEC 24747:2009.  */
#ifndef __STDC_WANT_MATH_SPEC_FUNCS__
# define __STDC_WANT_MATH_SPEC_FUNCS__ 1
#endif
/* Enable extensions on HP NonStop.  */
#ifndef _TANDEM_SOURCE
# define _TANDEM_SOURCE 1
#endif
/* Enable X/Open extensions.  Define to 500 only if necessary
   to make mbstate_t available.  */
#ifndef _XOPEN_SOURCE
/* # undef _XOPEN_SOURCE */
#endif


/* Version number of package */
#define VERSION "3.1.5"

/* Version label */
#define VERSION_LABEL ""

/* Version string */
#define VERSION_STRING "3.1.5"

/* Informational URL */
#define WIKI_URL "https://www.freeciv.org/"

/* Define WORDS_BIGENDIAN to 1 if your processor stores words with the most
   significant byte first (like Motorola and SPARC, unlike Intel). */
#if defined AC_APPLE_UNIVERSAL_BUILD
# if defined __BIG_ENDIAN__
#  define WORDS_BIGENDIAN 1
# endif
#else
# ifndef WORDS_BIGENDIAN
/* #  undef WORDS_BIGENDIAN */
# endif
#endif

/* Number of bits in a file offset, on hosts where this is settable. */
/* #undef _FILE_OFFSET_BITS */

/* Define to 1 if necessary to make fseeko visible. */
/* #undef _LARGEFILE_SOURCE */

/* Define to 1 on platforms where this makes off_t a 64-bit type. */
/* #undef _LARGE_FILES */

/* Number of bits in time_t, on hosts where this is settable. */
/* #undef _TIME_BITS */

/* Define to 1 on platforms where this makes time_t a 64-bit type. */
/* #undef __MINGW_USE_VC2005_COMPAT */

/* Define to empty if 'const' does not conform to ANSI C. */
/* #undef const */

/* Define to the type of a signed integer type wide enough to hold a pointer,
   if such a type exists, and if the system does not define it. */
/* #undef intptr_t */

/* Fallback since C++11 nullptr not available */
/* #undef nullptr */

/* Define as a signed integer type capable of holding a process identifier. */
/* #undef pid_t */

/* Define as 'fork' if 'vfork' does not work. */
/* #undef vfork */
