/* Generated by gen_headers/generate_version_header.sh. */

#ifndef FC__VERSION_GEN_H
#define FC__VERSION_GEN_H

#define MAJOR_VERSION 3
#define MINOR_VERSION 1
#define PATCH_VERSION 5
#ifndef VERSION_LABEL
#define VERSION_LABEL ""
#endif
#ifndef VERSION_STRING
#define VERSION_STRING "3.1.5"
#endif

#define NETWORK_CAPSTRING "+Freeciv-3.1-network city-original rsdesc32 obsinv ids32"

#ifndef FOLLOWTAG
#define FOLLOWTAG "stable"
#endif
#define FREECIV_DISTRIBUTOR ""

#endif /* FC__VERSION_GEN_H */
